#!/bin/bash

if test $# != 4; then
	echo "error: bad usage" >&2
	echo "try something like: $0 todo-all.txt  mem-stats.txt 56 2 > jobs-56gb.txt" >&2
	exit 1
fi

# todo is space separated csv file: thr, sigma
todo=$1
# space separated csv file (unique key): thr, sigma, maxmem
statsfile=$2
maxmem=$3
extramem=$4

! test -f "$todo" && echo "error: todo file does not exist '$todo'" >&2 && exit 1
! test -f "$statsfile" && echo "error: stats file does not exist '$statsfile'" >&2 && exit 1

awk '

function get_partner(availmem,      i)
{
	#print "get partner", j, left, "XXX", memstat[j]
	found = 0
	for (i in todo) {
		if ( todo[i] && memstat[i] < availmem) {
			if (!found || memstat[i] > memstat[found]) {
				found = i
			}
		}
	}
	if (found) {
		todo[found] = 0
		#print "found", found
		return found
	} else {
		#print "no partner found"
		return 0
	}
}

BEGIN {
	maxmem = '$maxmem' * 1024*1024
	extra = '$extramem' * 1024*1024

	while (getline < "'$todo'") {
		todo[$1" "$2]=1
	}
        while (getline < "'$statsfile'") {
                memstat[$1" "$2]=$3
	}

	for (t in todo) {

		#if (!todo[t]) continue
		#todo[t] = 0

		left = maxmem - extra
		j = 0
		while (partner = get_partner(left)) {
			#print "got one", partner
			jobs[j] = partner
			j++
			left -= memstat[partner]
		}
		if (cnt = j) {
			line = ""
			sum = 0
			for (j=0; j<cnt; j++) {
				sum +=  memstat[jobs[j]]
				line = line jobs[j]" "memstat[jobs[j]] " "
			}
			print "yo", cnt, sum, line
		}

	}


}
' < /dev/null

